-- Cart table to store shopping cart items
CREATE TABLE IF NOT EXISTS public.cart (
    cart_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    date_added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_id, inv_id)
);

-- Favorites table to store favorite items
CREATE TABLE IF NOT EXISTS public.favorites (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    date_added TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_id, inv_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_cart_account ON public.cart(account_id);
CREATE INDEX IF NOT EXISTS idx_favorites_account ON public.favorites(account_id);